### ISSUE TITLE
Can't install on GX 4.1.1.2 and 4.2.1

### ISSUE THREAD

**Issue by tilmanbremer** [mollie/gambio#1]
I know the release notes say 1.0.0 supports Gambio up to GX 4.0.x but we don't have a shop running with 4.0.x anymore. In GX 4.1 a critical error in the csv export was fixed that we urgently needed, so I can't downgrade either.

When I tried to activate the mollie plugin I got a white screen and it was not activated. That was the same in GX 4.1.1.2 and 4.2.1. Is there a schedule already to make the mollie plugin compatible with the latest versions of Gambio?

Thanks for your work otherwise, I am thrilled that we will finally get mollie in Gambio!

**Comment by logeecom** [comment]
Dear @tilmanbremer,

Thanks for reaching us. 

Our team released support for Gambio GX 4.1, 4.2, and 4.3 today. You can download the plugin from the following link: 

https://github.com/mollie/gambio/releases/tag/v2.0.1 

If you have any questions, please let us know.
Best regards.
