### ISSUE TITLE
Ciritcal error in the latest version.

### ISSUE THREAD

**Issue by Pixopax** [mollie/gambio#102]
Error in latest version:

I receive this error:

Mollie\BusinessLogic\Http\DTO\Link::fromArray(): Argument #1 ($raw) must be of type array, null given, 
called in /httpdocs/shop/GXModules/Mollie/Mollie/vendor/mollie/integration-core/src/BusinessLogic/Http/DTO/Payment.php on line 142

Ciritcal error:
Mollie\Gambio\Services\Business\OrderTransitionService::payOrder(): Argument #2 ($metadata) must be of type array, null given

httpdocs/shop/GXModules/Mollie/Mollie/Components/Services/Business/OrderTransitionService.php
line 22

This prevents the webhook from Mollie to my shop. 

Gambio 4.8.0.2
Mollie module 3.0.21

**Comment by Pixopax** [comment]
In the last 3 days I had 5 such errors. The payments seem ok, but the shop does not get any responses from Mollie anymore.

**Comment by asotela3911** [comment]
Hi @Pixopax  We are looking into the issue and will get back to you ASAP

**Comment by logeecom** [comment]
Hello @Pixopax,

Thank you for reaching out to us regarding this issue.

Please note that we fixed the reported issue and the changes in the module will be live with our next release.

We will let you know once the release is made.

Kind regards.

**Comment by logeecom** [comment]
Hello @Pixopax,

Note that our team has released new versions of the Mollie/Gambio modules:

[Release Release version 0.1.17 · mollie/gambio](https://github.com/mollie/gambio/releases/tag/v0.1.17)

[Release Release version 1.0.17 · mollie/gambio](https://github.com/mollie/gambio/releases/tag/v1.0.17)

[Release Release version 2.0.19 · mollie/gambio](https://github.com/mollie/gambio/releases/tag/v2.0.19)

[Release Release version 3.0.22 · mollie/gambio](https://github.com/mollie/gambio/releases/tag/v3.0.22)

Kind regards.
