### ISSUE TITLE
Class 'Mollie\BusinessLogic\Http\DTO\Issuer' not found

### ISSUE THREAD

**Issue by tuanthanh191996** [mollie/gambio#13]
Hi,
I'm using gambio v3.14.1.0
After install and add the api key to the module I have encounter an issue.
Class 'Mollie\BusinessLogic\Http\DTO\Issuer' not found in system\classes\external\mollie\vendor\mollie\integration-core\src\BusinessLogic\Http\DTO\PaymentMethod.php on line 44
Stack trace:
#0 system\classes\external\mollie\vendor\mollie\integration-core\src\BusinessLogic\Http\DTO\BaseDto.php(46): Mollie\BusinessLogic\Http\DTO\PaymentMethod::fromArray(Array)
#1 system\classes\external\mollie\vendor\mollie\integration-core\src\BusinessLogic\Http\Proxy.php(341): Mollie\BusinessLogic\Http\DTO\BaseDto::fromArrayBatch(Array)
#2 system\classes\external\mollie\vendor\mollie\integration-core\src\BusinessLogic\Http\Proxy.php(366): Mollie\BusinessLogic\Http\Proxy->getEnabledPaymentMethods(NULL, NULL, 'orders_api')
#3 system\classes\external\mollie\vendor\mollie\integration-core\src\BusinessLogic\PaymentMethod\PaymentMethodService.php(54): Mollie\BusinessLogic"
It's calling to the class Issuer but this class do not exists.
Please check it, thank you.

**Comment by logeecom** [comment]
HI @tuanthanh191996,

Thanks for reaching us.

Our team managed to reproduce and fix the reported issue. You can download the latest version here:
https://github.com/mollie/gambio/releases/tag/v0.1.4

We have also noticed (based on your stack trace) that your Mollie module structure is not for the Gambio v3.14.1.0 but for version 3.0 - 3.4. We strongly recommend using the Mollie version for Gambio 3.5-4.0 for the **Gambio v3.14.1.0**:
https://github.com/mollie/gambio/releases/tag/v1.0.3

**Important note:** If you decide to use the Mollie version for Gambio 3.5-4.0, please make sure first to delete all files related to the previous Mollie plugin version for 3.0-3.4 and then upload the Mollie version for Gambio 3.5-4.0.

Thank you so much for your attention and participation.
Best regards.
