### ISSUE TITLE
Lists of banks in iDEAL, KBC etc. broken and radio buttons overlap names.

### ISSUE THREAD

**Issue by tilmanbremer** [mollie/gambio#15]
I installed the latest version of the plugin (2.0.3.) today in our shop running Gambio 4.1.1.2. The lists in iDEAL, KBC etc. look like this:

![mollie](https://user-images.githubusercontent.com/20415107/103157588-97b77480-47b4-11eb-8d08-ddb5a65e7433.JPG)

The radio button has a left margin of -20 px. Also, the list doesnt seem to fit the container, so it breaks in pretty confusing ways. I honestly don't know if that is caused by some of our css settings, but I try to find anything related to that, but wasn't able to.

**Comment by logeecom** [comment]
Hi @tilmanbremer,

Thanks for reaching us.

Our team managed to reproduce this issue. This error occurs when the page cache is cleared before the modules and text cache upon module installation, so try clearing the page cache again, and the CSS and JS files should be added to the checkout page, which will correctly show the issuer’s list.

If the cache clearing doesn’t fix the issue, please provide us your shop URL, so we can check what is going on.

Thanks in advance.
Best regards.

**Comment by tilmanbremer** [comment]
Thank you for your fast response. I definitely emptied the caches multiple times after installing, that is usually the first thing I do with Gambio. Unfortunately, it didn't help. I just did it again, no changes.

The shop is not online at the moment, or at least the checkout isn't.

I think I am going to update Gambio to a newer version and try again. I can send you a link to the checkout January 1st, if the other steps didn't help.

**Comment by logeecom** [comment]
Hi @tilmanbremer,

Our team has checked once again, but we are not able to reproduce the issue. 

It is displayed correctly in all default Gambio themes.
![image](https://user-images.githubusercontent.com/20204230/103348899-a7c4a200-4a9b-11eb-9c5b-66fed295ff66.png)

Please send us a link to the checkout on January 1st.

Many thanks for considering our request.
Best regards.

**Comment by tilmanbremer** [comment]
Hi,
sorry for the delay, here is the shop. I was able to fix it temporarily by going for the dropdown option, which is fine, too. But I switched back so that you can have a look: https://bogensportshop.eu/en/

**Comment by tilmanbremer** [comment]
Hi, is it possible that someone has a look a this? I would like to set it back.

It not only looks broken, but the checkout page seems to automatically select and open the iDEAL payment option when I choose the radio button design. Really weird.

**Comment by logeecom** [comment]
Hi @tilmanbremer,

We managed to reproduce and fix the issue. This error occurs when the theme is changed to the Honeygrid (template) theme since, for this theme, asset files were not added to the checkout page.

We will release a new plugin version with this fix tomorrow.

Best regards.

**Comment by logeecom** [comment]
Hi @tilmanbremer,

We have released a new version to Github, please install the latest version 2.0.5.
https://github.com/mollie/gambio/releases/tag/v2.0.5

Best regards.
