### ISSUE TITLE
Can't install on GX 3.10.0.3

### ISSUE THREAD

**Issue by me-marcel** [mollie/gambio#2]
I recently tried to get the Branch https://github.com/mollie/gambio/tree/3.5-4.0 aka. release v1.0.1 working on Gambio GX 3.10.0.3. The branch states to be compatible with GX 3.5 - 4.0 though Gambio 3.10.0.3 wouldn't recognize the new module. All required caches were emptied after uploading the files to the webserver. Is the version confirmed to be working with GX 3.10.0.3? Thanks in advance.

**Comment by logeecom** [comment]
Hi @me-marcel,

Thanks for reaching us.

Our team has tested the plugin on different GX3 versions including 3.10.x.x. 

Did you upload the content of folder `gambio-1.0.x` to the root of Gambio shop? Only the content of folder `gambio-1.0.x` inside the downloaded zip should be uploaded to the root (please check the image below).

![image](https://user-images.githubusercontent.com/20204230/102792350-af53bf00-43a8-11eb-8c63-cfca02eb21c5.png)

Thanks in advance.
Best regards.

**Comment by me-marcel** [comment]
Hi @logeecom,

of course I followed the instructions. Since this is the exact process described within the README.md of the plugin I followed it step by step and cleared all caches after uploading the files shown in the screenshot above. Still the plugin doesn't show up as module, legacy module or payment method within GX v3.10.0.3.

Kind regards

**Comment by logeecom** [comment]
Hi @me-marcel,

Thanks for the detailed explanation. 

Could you please create a support ticket on [Mollie Support](https://help.mollie.com/hc/en-us)?

Please keep in mind that we will need admin and FTP access to check why Mollie doesn't show up as a module.

Thank you so much for your attention and participation.
Best regards.

**Comment by me-marcel** [comment]
I surely can 👍🏻 Thanks for taking time to deal with this issue.
