### ISSUE TITLE
Cancelled payment create a cancelled order, but product quantity is not restocked.

### ISSUE THREAD

**Issue by tilmanbremer** [mollie/gambio#21]
I noticed that, if customers use mollie in the checkout and they cancel the payment for whatever reason, an order is created, but it has the status "Cancelled". The big problem is, that the product quantity is not restocked and the delivery status is not recalculated. We have several options if I cancel an order manually:

- Restock product quantity
- Delivery status recalculate
- Reset article status

All of that has to happen, but it doesn't. The problem is that people are buying the last item, cancel the payment and then the item is sold out! So we are loosing purchases now, either because the people get frustrated and shop somewhere else, or they go for a different item instead.

Of course it also messes with our stock. I now have to manually set every cancelled order to a different order status (because you can't cancel a cancelled order in Gambio) and then cancel it again, with the above listed options checked.

It would be better of course if no order was created before the payment is not succesfull, like it happens with Paypal. But, if that isn't possible, at least I would need mollie to do the mentioned actions so that people can buy the item again.

**Comment by logeecom** [comment]
Hi @tilmanbremer 

Our team is working on a solution for this issue and that fix for the reported issue will be available at the beginning of next week.

Thanks for your patience.

**Comment by logeecom** [comment]
Hi @tilmanbremer 

We have implemented the fix, new plugin version is released. 

Please update the plugin to the latest version for Gambio 4.1:
https://github.com/mollie/gambio/releases/tag/v2.0.6

Best regards.
