### ISSUE TITLE
Can't cancel an order paid with mollie in the order overview

### ISSUE THREAD

**Issue by tilmanbremer** [mollie/gambio#22]
I am on Gambio 4.1.1.2, Mollie Plugin 2.0.4.

If a customer cancels the payment, the order is created but it gets the status "cancelled". The problem is, that the stock is not reset (issue #21), so I need to do this by hand.

If I change the order status to something else "processing" and than cancel it in the order list view (OrdersOverview), the shop throws an error and does not cancel the order:

> Die Bestellungen konnten nicht storniert werden. Nutzen Sie bitte stattdessen die Rückerstattungsoption.

That doesn't make sense to me, because I can't refund a cancelled payment. If I open the order and cancel it in the order details view, it works. The order is cancelled and the stock is reset (if I check the required options). But I still see an error:

> Mollie-Bestellung konnte nicht storniert werden. Antwort Mollie-API Unprocessable Entity: The payment cannot be cancelled.

I think the issue is, that cancelling an order and cancelling the payment are somehow connected, which is not ideal. With Paypal, those two are completely separated. I can cancel and refund any payment, also partly, and I can cancel orders and restock items without affecting the paypal payment.

**Comment by logeecom** [comment]
Hi @tilmanbremer,

Thanks for a detailed explanation and your input.  

Yes, you are correct. When an order is canceled in the shop, the integration will try to cancel payment on Mollie too. 

Since this requires a plugin behavior update, we will revise this behavior and let you know.

Best regards.

**Comment by logeecom** [comment]
Hi @tilmanbremer,

We have allowed order cancelation within the admin section. Merchants won’t get error message “Die Bestellungen konnten nicht storniert werden. Nutzen Sie bitte stattdessen die Rückerstattungsoption.“ anymore.

Please update the plugin to the latest version for Gambio 4.1:
https://github.com/mollie/gambio/releases/tag/v2.0.5

Best regards.
