### ISSUE TITLE
Mollie components iFrame is not displayed correctly

### ISSUE THREAD

**Issue by Peter-Oe** [mollie/gambio#31]
Hi, we have updated to the current version and saw, that the "Mollie components" is displayed incorrectly in the check out page. It's looks kind of buggy and also does not work with Test-Mode of the API. Maybe you can fix this with one of the next versions.

Edit 1: Also a little description inside the configuration would be helpful. Not sure, if everybody knows what "Mollie components" means - I also needed to Google it. 

Edit 2: When deactivating the "Mollie components" the layout is also not correct. Normally the chosen payment method would be highlighted with the primary colour (which is orange here obviously). With the current version it's not highlighted anymore.

"Mollie components" active: The German description is not completely inside the box. Also the grey background looks kind of oldschool and buggy within the payment method.
![mollie_components](https://user-images.githubusercontent.com/76442669/105872743-075e9080-5ffb-11eb-8dd2-afd944f329d6.png)

"Mollie components" deactivated: The Payment method is not highlighted anymore in the frontend. 
![payment_method](https://user-images.githubusercontent.com/76442669/105873553-e5b1d900-5ffb-11eb-8c0c-78f1728eaa47.png)

**Comment by logeecom** [comment]
Hi @Peter-Oe 

Thanks for reaching us.

Please find below the answers to your remarks.

_Edit 1: Also a little description inside the configuration would be helpful. Not sure, if everybody knows what "Mollie components" means - I also needed to Google it._
Thanks for the input, we will try to explain this a bit better in our next releases.

_Edit 2: When deactivating the "Mollie components" the layout is also not correct. Normally the chosen payment method would be highlighted with the primary colour (which is orange here obviously). With the current version it's not highlighted anymore._
Thanks for the input, we will try to set the same color in our next releases.

_"Mollie components" active: The German description is not completely inside the box. Also the grey background looks kind of oldschool and buggy within the payment method._
We have tried to reproduce the issue locally, but unfortunately, we didn't succeed. Please create a ticket on official molle support regarding this issue.

Best regards.

**Comment by Peter-Oe** [comment]
Hi @logeecom,

Thanks for the answer. Since we do not use the "Mollie components" option at the moment, I will not open a ticket yet. Just wanted to share my short experience here. If we need it in the future, I will do so.
