### ISSUE TITLE
not working with Gambio GX 4.5 

### ISSUE THREAD

**Issue by mediarex-de** [mollie/gambio#52]
Fatal error: Uncaught Error: Class 'StaticGXCoreLoader' not found in /GXModules/Mollie/Mollie/Components/Mappers/OrderMapper.php:34 Stack trace: #0 /GXModules/Mollie/Mollie/Components/BootstrapComponent.php(142): Mollie\Gambio\Mappers\OrderMapper->__construct() #1 /GXModules/Mollie/Mollie/Components/BootstrapComponent.php(121): Mollie\Gambio\BootstrapComponent::initProcessors() #2 /GXModules/Mollie/Mollie/vendor/mollie/integration-core/src/Infrastructure/BootstrapComponent.php(21): Mollie\Gambio\BootstrapComponent::initServices() #3 /GXModules/Mollie/Mollie/autoload.php(7): Mollie\Infrastructure\BootstrapComponent::init() #4 /GambioCore/Application/Bootstrapper/ModuleRegistration.php(71): require_once('/homepages/u681...') #5 /GambioCore/Application/Bootstrapper/ModuleRegistration.php(47): Gambio\Core\Application\Bo in /GXModules/Mollie/Mollie/Components/Mappers/OrderMapper.php on line 34

**Comment by logeecom** [comment]
Please note that the Mollie Gambio module currently does not support Gambio version 4.5 (as indicated on the [main module page](https://github.com/mollie/gambio)). We are working on making the module compatible with this release of the Gambio system. We will let you know once that compatibility is added.

**Comment by ristokekovic** [comment]
Please note that we have added the compatibility with Gambio versions 4.5.x. You can find a compatible module version on the [Releases](https://github.com/mollie/gambio/releases) page.
