### ISSUE TITLE
Page not loading with Gambio 4.6.0.2, fix

### ISSUE THREAD

**Issue by bagorob** [mollie/gambio#69]
GXModules/Mollie/Mollie/Admin/Overloads/AdminApplicationTopExtenderComponent/Mollie_AdminApplicationTopExtender.inc.php

Code:
public function proceed(): void

Change to Code:
public function proceed()

**Comment by tanjalog** [comment]
Hey @bagorob,

Please note that our development team has resolved your request.

We have removed void return value in GXModules/Mollie/Mollie/Admin/Overloads/AdminApplicationTopExtenderComponent/Mollie_AdminApplicationTopExtender.inc.php::proceed method and now it is fixed.

We will prepare a new release for the next week with changes made in https://github.com/mollie/gambio/issues/68 and we will keep you posted regarding this.

Best regards.

**Comment by tanjalog** [comment]
Hello @bagorob,

Thank you for your patience.

Please note as I already explained in a comment on the issue https://github.com/mollie/gambio/issues/68 that we will keep you posted regarding the new release next week.

Thank you for understanding.

Best regards.

**Comment by tanjalog** [comment]
Hello @bagorob,

Thank you for understanding the current situation.

Please note as I already explained in a comment on the issue https://github.com/mollie/gambio/issues/68 that we will keep you posted regarding the new release next week, cause we are experiencing some issues with permissions regarding the release.

Meanwhile, here is a new version plugin zip file v3.0.15(for Gambio 4.5-4.x), with changes from this ticket and changes from https://github.com/mollie/gambio/issues/68 ticket.

[gambio-3.0.15.zip](https://github.com/mollie/gambio/files/10184923/gambio-3.0.15.zip)


If you have any additional questions please feel free to contact us anytime.

Thanks,

Best regards

**Comment by tanjalog** [comment]
Hey @bagorob,

Thank you for your patience and understanding during resolving of this request.

Please note that all new plugin versions for:

Gambio 3.0.x - 3.4.x (v0.1.13),

Gambio 3.5.x - 4.0.x (v1.0.12),

Gambio 4.1.x - 4.4.x (v2.0.13),

Gambio 4.5.x - 4.x.x (v3.0.15)

are released.

As we inform you, the release also contains changes from https://github.com/mollie/gambio/issues/68.

Best regards.
